#!/usr/bin/env node

var auth = require('./routes/auth');
var bugs = require('./routes/bugs');

function post(req, res, ops){
    
    if ( req.url === '/mobileLogin' )
        auth.mobileLogin( req, res, ops );

    else
    if( req.url === '/mobileRegister' )
        auth.mobileRegister( req, res, ops );

    else
    if( req.url === '/verify_session' ) {
        console.log('[POST] verify_session');
        auth.validateSession( req, res, ops );
    }

    else
    if ( req.url === '/searchProduct' )
        bugs.searchProduct( req, res, ops );

    else
    if ( req.url === '/set-bug' )
        bugs.setBug( req, res, ops );

    else
    if ( req.url === '/update-bug' )
        bugs.updateProduct( req, res, ops );

    else
    if( req.url === '/setCover' )
        bugs.setCover( req, res, ops );

    else
    if( req.url === '/setTodayNumber')
        bugs.setTodayNumber( req, res, ops );

    else
    if( req.url === '/updateProfile' )
        auth.updateProfile( req, res, ops );

    
}



module.exports = post;
