#!/usr/bin/env node

var loader = require('./load');
var access = require('../utils/access');
var responses = require('../utils/responses')

function static( req, res ){

    var use = false;
    
    if( req.url === '/' ) {
        
        loader.loadHTML( './view/html/home.html', req, res );
        use = true;

    } else if(req.url === '/report-a-bug'){

        loader.loadHTML( './view/html/report-a-bug.html', req, res );
        use = true;

    } else if( req.url === '/signin'){

        loader.loadHTML( './view/html/login.html', req, res );
        use = true;

    } else if( req.url === '/signup'){

        loader.loadHTML( './view/html/signup.html', req, res );
        use = true;

    } else {

        loader.loadStaticFile( req.url, req, res );

    }
    
    return use;

}

module.exports = static;