#! /usr/bin/env node

var jwt = require('./jwt');
var cookie = require('cookie');
const { use } = require('chai');



function checkForAccess(bearer){

    var access = false;

    if(bearer){

        var authToken = bearer.split(" ")[1];
        
        if( authToken ){
            
            var decodedToken = jwt.decodeToken(authToken)
            
            if( decodedToken ){
                access = true;
            }
        }
    }
        
    return access;

}

module.exports = {
    checkForAccess
}