#!/usr/bin/env node

//var jwt = require('jwt-simple');
var jwt = require('jsonwebtoken');

var secret = process.env.SECRET || 'skghksdngjhkjjk34wdfn894jk3';


function createJsonWebToken(data){
    
    return jwt.sign( data, secret );

}

function decodeToken(token){

    console.log('token', token);
    
    try {

        var decoded = jwt.verify( token , secret );
        return decoded;
        
    } catch (error) {

        console.log('JWT Decoding Error:', error);
        return null;

    }

}


module.exports = {
    createJsonWebToken,
    decodeToken
}